networks:
  default:
    external: true 
    name: roboshop
services:
  # docker run -d --name mongodb --network=roboshop mongodb:v1
  mongodb:
    image: mongodb:v1
    container_name: mongodb

  catalogue:
   image: catalogue:v1 
   container_name: catalogue
   depends_on:
   - mongodb

  user:
   image: user:v1
   container_name: user
   depends_on:
   - mongodb
   - redis
  
  cart:
   image: cart:v1
   container_name: cart
   depends_on:
    - redis
    - catalogue

  # shipping: 
  #  image: shipping:v1
  #  depends_on: 
  #   - mysql

  redis:
    image: redis
    container_name: redis

  mysql:
     image: mysql:v1
     container_name: mysql

    
  web:
    image: web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    
  
    
