networks:
  default:
    external: true 
    name: roboshop
services:
  # docker run -d --name mongodb --network=roboshop mongodb:v1
  mongodb:
    image: mongodb:v1

  catalogue:
   image: catalogue:v1 
   depends_on:
   - mongodb

  user:
   image: user:v1
   depends_on:
   - mongodb
   - redis
  
  cart:
   image: cart:v1
   depends_on:
    - redis
    - catalogue

  # shipping: 
  #  image: shipping:v1
  #  depends_on: 
  #   - mysql

  redis:
    image: redis

  # mysql:
  #   image: mysql:v1

    
  web:
    image: web:v1
    ports:
      - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    
  
    
